USE [master]
GO
/****** Object:  Database [ControlTecDb]    Script Date: 22/11/2025 21:59:24 ******/
CREATE DATABASE [ControlTecDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ControlTecDb', FILENAME = N'C:\Users\poolg\OneDrive - INTEC\Escritorio\UNI\TRI 9\DESARROLLO DE APLICACIONES WEB\RETO WEB\BASE DE DATOControlTecDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ControlTecDb_log', FILENAME = N'C:\Users\poolg\OneDrive - INTEC\Escritorio\UNI\TRI 9\DESARROLLO DE APLICACIONES WEB\RETO WEB\BASE DE DATOControlTecDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ControlTecDb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ControlTecDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ControlTecDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ControlTecDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ControlTecDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ControlTecDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ControlTecDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [ControlTecDb] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ControlTecDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ControlTecDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ControlTecDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ControlTecDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ControlTecDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ControlTecDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ControlTecDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ControlTecDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ControlTecDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ControlTecDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ControlTecDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ControlTecDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ControlTecDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ControlTecDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ControlTecDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ControlTecDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ControlTecDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ControlTecDb] SET  MULTI_USER 
GO
ALTER DATABASE [ControlTecDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ControlTecDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ControlTecDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ControlTecDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ControlTecDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ControlTecDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [ControlTecDb] SET QUERY_STORE = OFF
GO
USE [ControlTecDb]
GO
/****** Object:  Table [dbo].[Documentos]    Script Date: 22/11/2025 21:59:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Documentos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Tipo] [nvarchar](50) NULL,
	[Ruta] [nvarchar](255) NULL,
	[SolicitudId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DocumentosRequeridos]    Script Date: 22/11/2025 21:59:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DocumentosRequeridos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[ServicioId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HistorialEstados]    Script Date: 22/11/2025 21:59:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HistorialEstados](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[SolicitudId] [int] NOT NULL,
	[EstadoAnterior] [nvarchar](50) NULL,
	[EstadoNuevo] [nvarchar](50) NOT NULL,
	[Comentario] [nvarchar](500) NULL,
	[UsuarioId] [int] NOT NULL,
	[FechaCambio] [datetime2](7) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Servicios]    Script Date: 22/11/2025 21:59:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Servicios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Descripcion] [nvarchar](255) NULL,
	[Costo] [decimal](18, 2) NULL,
	[RequierePago] [bit] NULL,
	[Activo] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Solicitudes]    Script Date: 22/11/2025 21:59:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Solicitudes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Estado] [nvarchar](50) NOT NULL,
	[FechaCreacion] [datetime] NOT NULL,
	[UsuarioId] [int] NULL,
	[ServicioId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Usuarios]    Script Date: 22/11/2025 21:59:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Usuarios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[Correo] [nvarchar](100) NOT NULL,
	[Contraseña] [nvarchar](100) NOT NULL,
	[Roll] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_HistorialEstados_SolicitudId]    Script Date: 22/11/2025 21:59:25 ******/
CREATE NONCLUSTERED INDEX [IX_HistorialEstados_SolicitudId] ON [dbo].[HistorialEstados]
(
	[SolicitudId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_HistorialEstados_UsuarioId]    Script Date: 22/11/2025 21:59:25 ******/
CREATE NONCLUSTERED INDEX [IX_HistorialEstados_UsuarioId] ON [dbo].[HistorialEstados]
(
	[UsuarioId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[HistorialEstados] ADD  DEFAULT (sysutcdatetime()) FOR [FechaCambio]
GO
ALTER TABLE [dbo].[Documentos]  WITH CHECK ADD FOREIGN KEY([SolicitudId])
REFERENCES [dbo].[Solicitudes] ([Id])
GO
ALTER TABLE [dbo].[DocumentosRequeridos]  WITH CHECK ADD FOREIGN KEY([ServicioId])
REFERENCES [dbo].[Servicios] ([Id])
GO
ALTER TABLE [dbo].[HistorialEstados]  WITH CHECK ADD  CONSTRAINT [FK_HistorialEstados_Solicitudes] FOREIGN KEY([SolicitudId])
REFERENCES [dbo].[Solicitudes] ([Id])
GO
ALTER TABLE [dbo].[HistorialEstados] CHECK CONSTRAINT [FK_HistorialEstados_Solicitudes]
GO
ALTER TABLE [dbo].[HistorialEstados]  WITH CHECK ADD  CONSTRAINT [FK_HistorialEstados_Usuarios] FOREIGN KEY([UsuarioId])
REFERENCES [dbo].[Usuarios] ([Id])
GO
ALTER TABLE [dbo].[HistorialEstados] CHECK CONSTRAINT [FK_HistorialEstados_Usuarios]
GO
ALTER TABLE [dbo].[Solicitudes]  WITH CHECK ADD FOREIGN KEY([ServicioId])
REFERENCES [dbo].[Servicios] ([Id])
GO
ALTER TABLE [dbo].[Solicitudes]  WITH CHECK ADD FOREIGN KEY([UsuarioId])
REFERENCES [dbo].[Usuarios] ([Id])
GO
USE [master]
GO
ALTER DATABASE [ControlTecDb] SET  READ_WRITE 
GO
